### ISSUE TITLE
traceback!!

### ISSUE THREAD

**Issue by ljh19930603** [wbond/asn1crypto#61] opened 2017-07-24 01:34 UTC
>>> from asn1crypto.keys import PublicKeyInfo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\asn1crypto\keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "C:\Python27\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "C:\Python27\lib\site-packages\asn1crypto\_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "C:\Python27\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 31, in <module>
    libcrypto_path = find_library('crypto')
  File "C:\Python27\lib\ctypes\util.py", line 53, in find_library
    fname = os.path.join(directory, name)
  File "C:\Python27\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 1: ordinal not in range(128)

**Comment by wbond** [comment] 2017-08-10 13:35
This seems to be a duplicate of #41. This has been fixed and will be part of the next release.

**Closed by wbond** 2017-08-10 13:35 UTC
